//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarriageRegistration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attorney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attorney()
        {
            this.MarriageRegisters = new HashSet<MarriageRegister>();
        }
    
        public int Id { get; set; }
        public string BrideAttorneyName { get; set; }
        public Nullable<int> MarriageRegistrationId { get; set; }
        public Nullable<int> BrideAttorneyNID { get; set; }
        public string BridegroomAttorneyName { get; set; }
        public Nullable<int> BridegroomAttorneyNID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarriageRegister> MarriageRegisters { get; set; }
    }
}
