//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarriageRegistration.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NationalID
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Birthday { get; set; }
        public string Address { get; set; }
        public string NID { get; set; }
        public string Gender { get; set; }
    }
}
